<application>
  <component name="RecentProjectsManager">
    <option name="recentPaths">
      <list>
        <option value="D:/Android Apps/Services" />
        <option value="D:/Android Apps/Notification" />
        <option value="D:/Android exercises/ud851-Exercises-student/ud851-Exercises-student/Lesson10-Hydration-Reminder/T10.01-Exercise-IntentServices" />
        <option value="D:/Android Apps" />
        <option value="D:/RoomWordSample" />
        <option value="D:/Android Apps/MyApplicationasd" />
        <option value="D:/Android exercises/ud851-Exercises-student/ud851-Exercises-student/Lesson09b-ToDo-List-AAC/T09b.01-Exercise-CreateEntity" />
        <option value="D:/Android exercises/ud851-Exercises-student/ud851-Exercises-student/Lesson09-ToDo-List/T09.01-Exercise-SetupContentProvider" />
        <option value="D:/Android exercises/ud851-Exercises-student/ud851-Exercises-student/Lesson08-Quiz-Example/T08.03-Exercise-FinishQuizExample" />
        <option value="D:/Android exercises/ud851-Exercises-student/ud851-Exercises-student/Lesson08-Quiz-Example/T08.02-Solution-AddAsyncTaskToRetrieveCursor" />
        <option value="D:/Android exercises/ud851-Exercises-student/ud851-Exercises-student/Lesson08-Quiz-Example/T08.02-Exercise-AddAsyncTaskToRetrieveCursor" />
        <option value="D:/Android exercises/ud851-Exercises-student/ud851-Exercises-student/Lesson08-Quiz-Example/T08.01-Exercise-AddTheContentProviderPermission" />
        <option value="D:/Android exercises/ud851-Sunshine-student/ud851-Sunshine-student/S06.03-Solution-PolishingPreferences" />
        <option value="D:/Android exercises/ud851-Sunshine-student/ud851-Sunshine-student/S06.03-Exercise-PolishingPreferences" />
        <option value="D:/Android exercises/ud851-Exercises-student/ud851-Exercises-student/Lesson06-Visualizer-Preferences/T06.10-Solution-EditTextPreferenceConstraints" />
        <option value="D:/Android exercises/ud851-Sunshine-student/ud851-Sunshine-student/S06.02-Solution-SettingsFragment" />
        <option value="D:/Android exercises/ud851-Sunshine-student/ud851-Sunshine-student/S06.02-Exercise-SettingsFragment" />
        <option value="D:/Android exercises/ud851-Sunshine-student/ud851-Sunshine-student/S06.01-Solution-LaunchSettingsActivity" />
        <option value="D:/Android exercises/ud851-Sunshine-student/ud851-Sunshine-student/S06.01-Exercise-LaunchSettingsActivity" />
        <option value="D:/Android exercises/ud851-Exercises-student/ud851-Exercises-student/Lesson06-Visualizer-Preferences/T06.10-Exercise-EditTextPreferenceConstraints" />
        <option value="D:/Android exercises/ud851-Exercises-student/ud851-Exercises-student/Lesson06-Visualizer-Preferences/T06.09-Solution-EditTextPreference" />
        <option value="D:/Android exercises/ud851-Exercises-student/ud851-Exercises-student/Lesson06-Visualizer-Preferences/T06.09-Exercise-EditTextPreference" />
        <option value="D:/Android exercises/ud851-Exercises-student/ud851-Exercises-student/Lesson06-Visualizer-Preferences/T06.08-Exercise-PreferenceSummary" />
        <option value="D:/Android exercises/ud851-Exercises-student/ud851-Exercises-student/Lesson06-Visualizer-Preferences/T06.07-Solution-ListPreference" />
        <option value="D:/Android exercises/ud851-Exercises-student/ud851-Exercises-student/Lesson06-Visualizer-Preferences/T06.07-Exercise-ListPreference" />
        <option value="D:/Android exercises/ud851-Exercises-student/ud851-Exercises-student/Lesson06-Visualizer-Preferences/T06.05-Exercise-PreferenceChangeListener" />
        <option value="D:/Android exercises/ud851-Exercises-student/ud851-Exercises-student/Lesson06-Visualizer-Preferences/T06.04-Exercise-UseResources" />
        <option value="D:/Android exercises/ud851-Exercises-student/ud851-Exercises-student/Lesson06-Visualizer-Preferences/T06.03-Exercise-ReadingFromSharedPreferences" />
        <option value="D:/Android exercises/ud851-Exercises-student/ud851-Exercises-student/Lesson06-Visualizer-Preferences/T06.02-Exercise-MakeAPreferenceFragment" />
        <option value="D:/Android exercises/ud851-Exercises-student/ud851-Exercises-student/Lesson06-Visualizer-Preferences/T06.01-Exercise-SetupTheActivity" />
        <option value="D:/Android exercises/ud851-Sunshine-student/ud851-Sunshine-student/S03.02-Solution-RecyclerViewClickHandling" />
        <option value="D:/Android exercises/ud851-Sunshine-student/ud851-Sunshine-student/S03.02-Exercise-RecyclerViewClickHandling" />
        <option value="D:/Android exercises/ud851-Sunshine-student/ud851-Sunshine-student/S03.01-Solution-RecyclerView" />
        <option value="D:/Android exercises/ud851-Exercises-student/ud851-Exercises-student/Lesson03-Green-Recycler-View/T03.04-Solution-WiringUpRecyclerView" />
        <option value="D:/Android exercises/ud851-Sunshine-student/ud851-Sunshine-student/S03.01-Exercise-RecyclerView" />
        <option value="D:/Android exercises/ud851-Exercises-student/ud851-Exercises-student/Lesson03-Green-Recycler-View/T03.07-Solution-RecyclerViewClickHandling" />
        <option value="D:/Android exercises/ud851-Exercises-student/ud851-Exercises-student/Lesson03-Green-Recycler-View/T03.07-Exercise-RecyclerViewClickHandling" />
        <option value="D:/Android exercises/ud851-Exercises